"use strict";

module.exports = {
  up: async (queryInterface, Sequelize) => {
    await queryInterface.bulkInsert(
      "posts",
      [
        {
          uuid: "023c05af-90b5-49bb-b6b3-7c284e0428c6",
          name: "회사원셔츠 4종세트",
          image: "/images/man-shirts-1.jpg",
          thumbnail: [
            "/images/man-shirts-1.jpg",
            "/images/man-shirts-2.png",
            "/images/footwear-1.png",
            "/images/footwear-2.png",
          ],
          description:
            "옷장에 하나쯤은 있어야 할 머스트 해브 아이템! 캐주얼 또는 포멀룩 어디에도 매칭할 수 있는 폴라 보이즈 옥스포트 셔츠",
          brand: "폴라",
          category: "남자정장",
          size: [95, 100, 105, 110],
          sizeRemain: [3, 4, 10, 13],
          price: 120000,
          countInStock: 30,
          rating: 2.1,
          numReviews: 13,
          sale: 30,
          freeShipping: true,
          deliveryFee: 0,
          createdAt: "2021-01-01",
          updatedAt: "2021-01-01",
        },
        {
          uuid: "041c07af-90b5-49bb-b6b3-7c284e0428c6",
          name: "회사원셔츠 2종세트",
          image: "/images/man-shirts-2.png",
          thumbnail: [
            "/images/man-shirts-1.jpg",
            "/images/man-shirts-2.png",
            "/images/footwear-1.png",
            "/images/footwear-2.png",
          ],
          description:
            "간절기 머스트 해브 아이템!!! 회사원 셔츠를 알뜰하게 구매해 보세요!",
          brand: "플로랄프로란",
          category: "남자정장",
          size: [95, 100, 105, 110],
          sizeRemain: [5, 5, 5, 5],
          price: 90000,
          countInStock: 20,
          rating: 4.7,
          numReviews: 11,
          sale: 10,
          freeShipping: false,
          deliveryFee: 3500,
          createdAt: "2021-01-01",
          updatedAt: "2021-01-01",
        },
        {
          uuid: "041c05af-90b5-49bb-b8b1-7c284e0428c6",
          name: "신입사원 정장세트",
          image: "/images/apparel-1.png",
          thumbnail: [
            "/images/man-shirts-1.jpg",
            "/images/man-shirts-2.png",
            "/images/footwear-1.png",
            "/images/footwear-2.png",
          ],
          description: "멀란지그레이 하운드투스 익스트림 하프 정장",
          brand: "지이크파란오비",
          category: "남자정장",
          size: [95, 100, 105, 110],
          sizeRemain: [5, 5, 5, 5],
          price: 500000,
          countInStock: 20,
          rating: 4.3,
          numReviews: 9,
          sale: 20,
          freeShipping: false,
          deliveryFee: 2500,
          createdAt: "2021-01-01",
          updatedAt: "2021-01-01",
        },

        {
          uuid: "041c05af-10b2-49bd-b6b3-7c284e0428c6",
          name: "에어조던 23 시리즈",
          image: "/images/footwear-1.png",
          thumbnail: [
            "/images/man-shirts-1.jpg",
            "/images/man-shirts-2.png",
            "/images/footwear-1.png",
            "/images/footwear-2.png",
          ],
          description: "다시 돌아온 에어조던 시리즈",
          brand: "나이스",
          category: "운동화",
          size: [240, 250, 260, 270, 280, 290],
          sizeRemain: [5, 5, 5, 5, 3, 2],
          price: 200000,
          countInStock: 25,
          rating: 4.9,
          numReviews: 50,
          sale: 20,
          freeShipping: false,
          deliveryFee: 3500,
          createdAt: "2021-01-01",
          updatedAt: "2021-01-01",
        },

        {
          uuid: "041c05af-90b5-49bb-a6a3-7c284e0428c6",
          name: "발렌시아 운동화",
          image: "/images/footwear-2.png",
          thumbnail: [
            "/images/man-shirts-1.jpg",
            "/images/man-shirts-2.png",
            "/images/footwear-1.png",
            "/images/footwear-2.png",
          ],
          description: "수식어가 필요없는 명품 운동화",
          brand: "발렌시아",
          category: "운동화",
          size: [240, 250, 260, 270, 280, 290],
          sizeRemain: [1, 1, 1, 3, 3, 1],
          price: 1200000,
          countInStock: 9,
          rating: 4.1,
          numReviews: 10,
          sale: 20,
          freeShipping: true,
          deliveryFee: 3500,
          createdAt: "2021-01-01",
          updatedAt: "2021-01-01",
        },
        {
          uuid: "041c05af-90b5-49bb-b6b3-7c574e0428c6",
          name: "여자 정장 일자바지 슬랙스",
          image: "/images/woman-pants1.png",
          thumbnail: [
            "/images/man-shirts-1.jpg",
            "/images/man-shirts-2.png",
            "/images/footwear-1.png",
            "/images/footwear-2.png",
          ],
          description: "가성비 최고, 색감과 핏감 모두 완벽한 일자핏 정장슬랙스",
          brand: "바이더웨이텐",
          category: "여자정장",
          size: [44, 55, 66, 77],
          sizeRemain: [30, 20, 20, 3],
          price: 50000,
          countInStock: 73,
          rating: 4.9,
          numReviews: 87,
          sale: 10,
          freeShipping: false,
          deliveryFee: 4000,
          createdAt: "2021-01-01",
          updatedAt: "2021-01-01",
        },
      ],
      {}
    );
  },

  down: async (queryInterface, Sequelize) => {
    await queryInterface.bulkDelete("posts", null, {});
  },
};
