name: "Terraform-Normal-Deploy"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform-Normal-Deploy"

    env:
      # working-directory: ./scripts_terraform
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    runs-on: ubuntu-latest

    steps:
      - name: employ files
        uses: actions/checkout@v3

      - name: terraform normal deploy
        # shell: bash
        run: |
          ls -al
          export VERSION=${{github.run_number}}          
          chmod +x ./scripts_terraform/script/deploy.prod.normal.sh
          ./scripts_terraform/script/deploy.prod.normal.sh
