FROM node:14.15.3-alpine3.11

RUN apk add --no-cache openssl

ENV DOCKERIZE_VERSION v0.6.1

RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

WORKDIR /app/server

ENV PATH /app/server/node_modules/.bin:$PATH

COPY ./package.json ./

RUN npm i --no-optional && npm cache clean --force

COPY ./ ./

# RUN sudo chmod +x docker-entrypoint.sh

ENTRYPOINT ["/bin/sh","./docker-entrypoint.sh"]

