FROM node:14.15.3-alpine3.11
# FROM node:16-alpine3.14

WORKDIR /app/client

ENV PATH /app/client/node_modules/.bin:$PATH

COPY ./package.json ./

RUN npm i --no-optional && npm cache clean --force

COPY ./ ./

ENTRYPOINT ["/bin/sh","./docker-entrypoint.sh"]

