// Address Request
export const DEFAULT_ADDRESS_REQUEST = "DEFAULT_ADDRESS_REQUEST";
export const DEFAULT_ADDRESS_SUCCESS = "DEFAULT_ADDRESS_SUCCESS";
export const DEFAULT_ADDRESS_FAILURE = "DEFAULT_ADDRESS_FAILURE";

// Latest Request
export const LATEST_ADDRESS_REQUEST = "LATEST_ADDRESS_REQUEST";
export const LATEST_ADDRESS_SUCCESS = "LATEST_ADDRESS_SUCCESS";
export const LATEST_ADDRESS_FAILURE = "LATEST_ADDRESS_FAILURE";

// Save Address
export const SAVE_ADDRESS_REQUEST = "SAVE_ADDRESS_REQUEST";
export const SAVE_ADDRESS_SUCCESS = "SAVE_ADDRESS_SUCCESS";
export const SAVE_ADDRESS_FAILURE = "SAVE_ADDRESS_FAILURE";

// Radio
export const RADIO_SET_REQUEST = "RADIO_SET_REQUEST";
export const RADIO_SET_SUCCESS = "RADIO_SET_SUCCESS";
export const RADIO_SET_FAILURE = "RADIO_SET_FAILURE";

// Radio Open
export const RADIO_MODAL_REQUEST = "RADIO_MODAL_REQUEST";
export const RADIO_MODAL_SUCCESS = "RADIO_MODAL_SUCCESS";
export const RADIO_MODAL_FAILURE = "RADIO_MODAL_FAILURE";

// Radio Close
export const RADIO_MODAL_CLOSE_REQUEST = "RADIO_MODAL_CLOSE_REQUEST";
export const RADIO_MODAL_CLOSE_SUCCESS = "RADIO_MODAL_CLOSE_SUCCESS";
export const RADIO_MODAL_CLOSE_FAILURE = "RADIO_MODAL_CLOSE_FAILURE";
