// Admin Summary Request
export const ADMIN_SUMMARY_REQUEST = "ADMIN_SUMMARY_REQUEST";
export const ADMIN_SUMMARY_SUCCESS = "ADMIN_SUMMARY_SUCCESS";
export const ADMIN_SUMMARY_FAILURE = "ADMIN_SUMMARY_FAILURE";

// Admin User Request
export const ADMIN_USER_REQUEST = "ADMIN_USER_REQUEST";
export const ADMIN_USER_SUCCESS = "ADMIN_USER_SUCCESS";
export const ADMIN_USER_FAILURE = "ADMIN_USER_FAILURE";

// Make Admin User
export const MAKE_ADMIN_USER_REQUEST = "MAKE_ADMIN_USER_REQUEST";
export const MAKE_ADMIN_USER_SUCCESS = "MAKE_ADMIN_USER_SUCCESS";
export const MAKE_ADMIN_USER_FAILURE = "MAKE_ADMIN_USER_FAILURE";

// Delete Admin User
export const DELETE_ADMIN_USER_REQUEST = "DELETE_ADMIN_USER_REQUEST";
export const DELETE_ADMIN_USER_SUCCESS = "DELETE_ADMIN_USER_SUCCESS";
export const DELETE_ADMIN_USER_FAILURE = "DELETE_ADMIN_USER_FAILURE";

// initalize Password
export const INITIALIZE_PASSWORD_REQUEST = "INITIALIZE_PASSWORD_REQUEST";
export const INITIALIZE_PASSWORD_SUCCESS = "INITIALIZE_PASSWORD_SUCCESS";
export const INITIALIZE_PASSWORD_FAILURE = "INITIALIZE_PASSWORD_FAILURE";

// Post Request
export const ADMIN_POST_REQUEST = "ADMIN_POST_REQUEST";
export const ADMIN_POST_SUCCESS = "ADMIN_POST_SUCCESS";
export const ADMIN_POST_FAILURE = "ADMIN_POST_FAILURE";

// Delete Post
export const DELETE_ADMIN_POST_REQUEST = "DELETE_ADMIN_POST_REQUEST";
export const DELETE_ADMIN_POST_SUCCESS = "DELETE_ADMIN_POST_SUCCESS";
export const DELETE_ADMIN_POST_FAILURE = "DELETE_ADMIN_POST_FAILURE";

// Delete Post
export const ADMIN_PRODUCT_ONE_LOAD_POST_REQUEST =
  "ADMIN_PRODUCT_ONE_LOAD_POST_REQUEST";
export const ADMIN_PRODUCT_ONE_LOAD_POST_SUCCESS =
  "ADMIN_PRODUCT_ONE_LOAD_POST_SUCCESS";
export const ADMIN_PRODUCT_ONE_LOAD_POST_FAILURE =
  "ADMIN_PRODUCT_ONE_LOAD_POST_FAILURE";

// Delete loaded MainImage
export const MAIN_IMAGE_DELETE_REQUEST = "MAIN_IMAGE_DELETE_REQUEST";
export const MAIN_IMAGE_DELETE_SUCCESS = "MAIN_IMAGE_DELETE_SUCCESS";
export const MAIN_IMAGE_DELETE_FAILURE = "MAIN_IMAGE_DELETE_FAILURE";

// Delete loaded MainImage
export const THUMBNAIL_IMAGE_DELETE_REQUEST = "THUMBNAIL_IMAGE_DELETE_REQUEST";
export const THUMBNAIL_IMAGE_DELETE_SUCCESS = "THUMBNAIL_IMAGE_DELETE_SUCCESS";
export const THUMBNAIL_IMAGE_DELETE_FAILURE = "THUMBNAIL_IMAGE_DELETE_FAILURE";

// PRODUCT Modify REQUEST
export const PRODUCT_IMAGE_MODIFY_REQUEST = "PRODUCT_IMAGE_MODIFY_REQUEST";
export const PRODUCT_IMAGE_MODIFY_SUCCESS = "PRODUCT_IMAGE_MODIFY_SUCCESS";
export const PRODUCT_IMAGE_MODIFY_FAILURE = "PRODUCT_IMAGE_MODIFY_FAILURE";

// Admin Order List
export const ADMIN_ORDER_LIST_REQUEST = "ADMIN_ORDER_LIST_REQUEST";
export const ADMIN_ORDER_LIST_SUCCESS = "ADMIN_ORDER_LIST_SUCCESS";
export const ADMIN_ORDER_LIST_FAILURE = "ADMIN_ORDER_LIST_FAILURE";

// Admin TrackingNumber Modify
export const ADMIN_TRACKING_NUMBER_REQUEST = "ADMIN_TRACKING_NUMBER_REQUEST";
export const ADMIN_TRACKING_NUMBER_SUCCESS = "ADMIN_TRACKING_NUMBER_SUCCESS";
export const ADMIN_TRACKING_NUMBER_FAILURE = "ADMIN_TRACKING_NUMBER_FAILURE";

// Admin Review
export const ADMIN_REVIEW_REQUEST = "ADMIN_REVIEW_REQUEST";
export const ADMIN_REVIEW_SUCCESS = "ADMIN_REVIEW_SUCCESS";
export const ADMIN_REVIEW_FAILURE = "ADMIN_REVIEW_FAILURE";

// Admin Delete Review
export const ADMIN_DELETE_REVIEW_REQUEST = "ADMIN_DELETE_REVIEW_REQUEST";
export const ADMIN_DELETE_REVIEW_SUCCESS = "ADMIN_DELETE_REVIEW_SUCCESS";
export const ADMIN_DELETE_REVIEW_FAILURE = "ADMIN_DELETE_REVIEW_FAILURE";

// Admin Search Product
export const ADMIN_SEARCH_REQUEST = "ADMIN_SEARCH_REQUEST";
export const ADMIN_SEARCH_SUCCESS = "ADMIN_SEARCH_SUCCESS";
export const ADMIN_SEARCH_FAILURE = "ADMIN_SEARCH_FAILURE";
