// SIGNUP
export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

// NORMAL LOGIN
export const NORMAL_LOGIN_REQUEST = "NORMAL_LOGIN_REQUEST";
export const NORMAL_LOGIN_SUCCESS = "NORMAL_LOGIN_SUCCESS";
export const NORMAL_LOGIN_FAILURE = "NORMAL_LOGIN_FAILURE";

// GOOGLE_LOGIN
export const GOOGLE_API_REQUEST = "GOOGLE_API_REQUEST";
export const GOOGLE_API_SUCCESS = "GOOGLE_API_SUCCESS";
export const GOOGLE_API_FAILURE = "GOOGLE_API_FAILURE";

// NAVER LOGIN API
export const NAVER_API_REQUEST = "NAVER_API_REQUEST";
export const NAVER_API_SUCCESS = "NAVER_API_SUCCESS";
export const NAVER_API_FAILURE = "NAVER_API_FAILURE";

// KAKAO LOGIN API
export const KAKAO_API_REQUEST = "KAKAO_API_REQUEST";
export const KAKAO_API_SUCCESS = "KAKAO_API_SUCCESS";
export const KAKAO_API_FAILURE = "KAKAO_API_FAILURE";

// LOGIN CHECK
export const LOGIN_CHECK_REQUEST = "LOGIN_CHECK_REQUEST";
export const LOGIN_CHECK_SUCCESS = "LOGIN_CHECK_SUCCESS";
export const LOGIN_CHECK_FAILURE = "LOGIN_CHECK_FAILURE";

// REFRESH ACCESS TOKEN
export const REFRESH_ACCESSTOKEN_GET_SUCCESS =
  "REFRESH_ACCESSTOKEN_GET_SUCCESS";
export const REFRESH_ACCESSTOKEN_GET_FAILURE =
  "REFRESH_ACCESSTOKEN_GET_FAILURE";

// LOGOUT API
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

// EMAIL TOKEN AUTH
export const EMAIL_TOKEN_AUTH_REQUEST = "EMAIL_TOKEN_AUTH_REQUEST";
export const EMAIL_TOKEN_AUTH_SUCCESS = "EMAIL_TOKEN_AUTH_SUCCESS";
export const EMAIL_TOKEN_AUTH_FAILURE = "EMAIL_TOKEN_AUTH_FAILURE";

// LOGIN ERROR CLEAR
export const LOGIN_ERROR_CLEAR_REQUEST = "LOGIN_ERROR_CLEAR_REQUEST";
export const LOGIN_ERROR_CLEAR_SUCCESS = "LOGIN_ERROR_CLEAR_SUCCESS";
export const LOGIN_ERROR_CLEAR_FAILURE = "LOGIN_ERROR_CLEAR_FAILURE";
