// CART ITEM REQUEST(deprecated)
// export const CART_ITEM_REQUEST = "CART_ITEM_REQUEST";
// export const CART_ITEM_SUCCESS = "CART_ITEM_SUCCESS";
// export const CART_ITEM_FAILURE = "CART_ITEM_FAILURE";

// CART ADD ITEM
export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST";
export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS";
export const CART_ADD_ITEM_FAILURE = "CART_ADD_ITEM_FAILURE";

// CART ADD ITEM
export const CART_LOAD_ITEM_REQUEST = "CART_LOAD_ITEM_REQUEST";
export const CART_LOAD_ITEM_SUCCESS = "CART_LOAD_ITEM_SUCCESS";
export const CART_LOAD_ITEM_FAILURE = "CART_LOAD_ITEM_FAILURE";

// CART REMOVE ITEM
export const CART_REMOVE_ITEM_REQUEST = "CART_REMOVE_ITEM_REQUEST";
export const CART_REMOVE_ITEM_SUCCESS = "CART_REMOVE_ITEM_SUCCESS";
export const CART_REMOVE_ITEM_FAILURE = "CART_REMOVE_ITEM_FAILURE";

// ORDER SUBMIT ITEM
export const ORDER_SUBMIT_REQUEST = "ORDER_SUBMIT_REQUEST";
export const ORDER_SUBMIT_SUCCESS = "ORDER_SUBMIT_SUCCESS";
export const ORDER_SUBMIT_FAILURE = "ORDER_SUBMIT_FAILURE";

// Shipping Request
export const SHIPPING_LOAD_REQUEST = "SHIPPING_LOAD_REQUEST";
export const SHIPPING_LOAD_SUCCESS = "SHIPPING_LOAD_SUCCESS";
export const SHIPPING_LOAD_FAILURE = "SHIPPING_LOAD_FAILURE";

// My Shipping Request
export const CHECK_MY_SHIPPING_REQUEST = "CHECK_MY_SHIPPING_REQUEST";
export const CHECK_MY_SHIPPING_SUCCESS = "CHECK_MY_SHIPPING_SUCCESS";
export const CHECK_MY_SHIPPING_FAILURE = "CHECK_MY_SHIPPING_FAILURE";

// Create Review
export const CREATE_REVIEW_REQUEST = "CREATE_REVIEW_REQUEST";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAILURE = "CREATE_REVIEW_FAILURE";

// Check Review
export const CHECK_REVIEW_REQUEST = "CHECK_REVIEW_REQUEST";
export const CHECK_REVIEW_SUCCESS = "CHECK_REVIEW_SUCCESS";
export const CHECK_REVIEW_FAILURE = "CHECK_REVIEW_FAILURE";
// 페이지가 다시 렌더링 되면서 리뷰했는지 체크한다. 리뷰했으면 리뷰완료로 나옴

// Update Review
export const UPDATE_OPEN_REQUEST = "UPDATE_OPEN_REQUEST";
export const UPDATE_OPEN_SUCCESS = "UPDATE_OPEN_SUCCESS";
export const UPDATE_OPEN_FAILURE = "UPDATE_OPEN_FAILURE";

// Update Review
export const UPDATE_REVIEW_REQUEST = "UPDATE_REVIEW_REQUEST";
export const UPDATE_REVIEW_SUCCESS = "UPDATE_REVIEW_SUCCESS";
export const UPDATE_REVIEW_FAILURE = "UPDATE_REVIEW_FAILURE";
// 페이지가 다시 렌더링 되면서 리뷰했는지 체크한다. 리뷰했으면 리뷰완료로 나옴
