// Mypage Password Change
export const MYPAGE_PASSWORD_CHANGE_REQUEST = "MYPAGE_PASSWORD_CHANGE_REQUEST";
export const MYPAGE_PASSWORD_CHANGE_SUCCESS = "MYPAGE_PASSWORD_CHANGE_SUCCESS";
export const MYPAGE_PASSWORD_CHANGE_FAILURE = "MYPAGE_PASSWORD_CHANGE_FAILURE";
