// KAKAO PAY
export const KAKAO_PAY_REQUEST = "KAKAO_PAY_REQUEST";
export const KAKAO_PAY_SUCCESS = "KAKAO_PAY_SUCCESS";
export const KAKAO_PAY_FAILURE = "KAKAO_PAY_FAILURE";

// KAKAO PAY
export const ORDER_ITEMS_RESET_REQUEST = "ORDER_ITEMS_RESET_REQUEST";
export const ORDER_ITEMS_RESET_SUCCESS = "ORDER_ITEMS_RESET_SUCCESS";
export const ORDER_ITEMS_RESET_FAILURE = "ORDER_ITEMS_RESET_FAILURE";

// Modal Open
export const MODAL_OPEN_REQUEST = "MODAL_OPEN_REQUEST";
export const MODAL_OPEN_SUCCESS = "MODAL_OPEN_SUCCESS";
export const MODAL_OPEN_FAILURE = "MODAL_OPEN_FAILURE";

// Modal Sucess Close
export const MODAL_SUCCESS_CLOSE_REQUEST = "MODAL_SUCCESS_CLOSE_REQUEST";
export const MODAL_SUCCESS_CLOSE_SUCCESS = "MODAL_SUCCESS_CLOSE_SUCCESS";
export const MODAL_SUCCESS_CLOSE_FAILURE = "MODAL_SUCCESS_CLOSE_FAILURE";

// Modal Cancel Close
export const MODAL_CANCEL_CLOSE_REQUEST = "MODAL_CANCEL_CLOSE_REQUEST";
export const MODAL_CANCEL_CLOSE_SUCCESS = "MODAL_CANCEL_CLOSE_SUCCESS";
export const MODAL_CANCEL_CLOSE_FAILURE = "MODAL_CANCEL_CLOSE_FAILURE";

// Modal Failure Close
export const MODAL_FAILURE_CLOSE_REQUEST = "MODAL_FAILURE_CLOSE_REQUEST";
export const MODAL_FAILURE_CLOSE_SUCCESS = "MODAL_FAILURE_CLOSE_SUCCESS";
export const MODAL_FAILURE_CLOSE_FAILURE = "MODAL_FAILURE_CLOSE_FAILURE";

// kakao Pay Cancel Info Save
export const KAKAO_PAY_CANCEL_INFO_SAVE_REQUEST =
  "KAKAO_PAY_CANCEL_INFO_SAVE_REQUEST";
export const KAKAO_PAY_CANCEL_INFO_SAVE_SUCCESS =
  "KAKAO_PAY_CANCEL_INFO_SAVE_SUCCESS";
export const KAKAO_PAY_CANCEL_INFO_SAVE_FAILURE =
  "KAKAO_PAY_CANCEL_INFO_SAVE_FAILURE";
//
export const KAKAO_PAY_CANCEL_REQUEST = "KAKAO_PAY_CANCEL_REQUEST";
export const KAKAO_PAY_CANCEL_SUCCESS = "KAKAO_PAY_CANCEL_SUCCESS";
export const KAKAO_PAY_CANCEL_FAILURE = "KAKAO_PAY_CANCEL_FAILURE";
