// POST LOADING REQUEST
export const PRODUCT_LOADING_REQUEST = "PRODUCT_LOADING_REQUEST";
export const PRODUCT_LOADING_SUCCESS = "PRODUCT_LOADING_SUCCESS";
export const PRODUCT_LOADING_FAILURE = "PRODUCT_LOADING_FAILUER";

// PRODUCT ONE LOADING REQUEST
export const PRODUCT_ONE_LOADING_REQUEST = "PRODUCT_ONE_LOADING_REQUEST";
export const PRODUCT_ONE_LOADING_SUCCESS = "PRODUCT_ONE_LOADING_SUCCESS";
export const PRODUCT_ONE_LOADING_FAILURE = "PRODUCT_ONE_LOADING_FAILUER";

// PRODUCT ONE LOADING REQUEST
export const PRODUCT_UPLOAD_REQUEST = "PRODUCT_UPLOAD_REQUEST";
export const PRODUCT_UPLOAD_SUCCESS = "PRODUCT_UPLOAD_SUCCESS";
export const PRODUCT_UPLOAD_FAILURE = "PRODUCT_UPLOAD_FAILURE";

// PRODUCT Image Delete REQUEST
export const PRODUCT_IMAGE_DELETE_REQUEST = "PRODUCT_IMAGE_DELETE_REQUEST";
export const PRODUCT_IMAGE_DELETE_SUCCESS = "PRODUCT_IMAGE_DELETE_SUCCESS";
export const PRODUCT_IMAGE_DELETE_FAILURE = "PRODUCT_IMAGE_DELETE_FAILURE";

// PRODUCT Thumbnail Image Delete REQUEST
export const PRODUCT_THUMBNAIL_DELETE_REQUEST =
  "PRODUCT_THUMBNAIL_DELETE_REQUEST";
export const PRODUCT_THUMBNAIL_DELETE_SUCCESS =
  "PRODUCT_THUMBNAIL_DELETE_SUCCESS";
export const PRODUCT_THUMBNAIL_DELETE_FAILURE =
  "PRODUCT_THUMBNAIL_DELETE_FAILURE";

// PRODUCT Modify REQUEST
export const PRODUCT_NOIMAGE_MODIFY_REQUEST = "PRODUCT_NOIMAGE_MODIFY_REQUEST";
export const PRODUCT_NOIMAGE_MODIFY_SUCCESS = "PRODUCT_NOIMAGE_MODIFY_SUCCESS";
export const PRODUCT_NOIMAGE_MODIFY_FAILURE = "PRODUCT_NOIMAGE_MODIFY_FAILURE";

// PRODUCT SEARCH REQUEST
export const PRODUCT_SEARCH_REQUEST = "PRODUCT_SEARCH_REQUEST";
export const PRODUCT_SEARCH_SUCCESS = "PRODUCT_SEARCH_SUCCESS";
export const PRODUCT_SEARCH_FAILURE = "PRODUCT_SEARCH_FAILURE";
